# enable throttling
throttlingEnabled: true
# total qps limit - i.e. number of allowed requests per second
totalQPS: 30
#default tenant qps limit
defaultQPS: 5
# qps per tenant
tenants:
  "my_favorite_tenant" : 25
#exceptions
exceptions:
  - "testtenant"
  - "graphite_cluster"


